name: Generate GitHub Metrics
on:
  schedule:
    - cron: '30 0 * * *' # daily at 00:30 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SaiiPrashanth
          template: classic
          filename: github-metrics.svg
          base: header, activity, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_indepth: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_lines: yes
          plugin_traffic: yes
