name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write   # to push output branch

concurrency:
  group: snake-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: SaiiPrashanth
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00ffff&color_dots=#0a0a0a,#1a1a1a,#2a2a2a,#00ffff
      - name: List generated files
        run: |
          ls -R dist || (echo 'dist missing' && exit 1)
      - name: Push snake to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          force_orphan: true