name: Generate Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: SaiiPrashanth
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add dist/github-contribution-grid-snake.svg || true
          git commit -m "chore: update snake" || echo "No changes"
          git push
